---

- hosts: all
  become: true
  pre_tasks:


  - name: Updates CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"    

  - name: Updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"    



- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes



- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    tags: db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"    




- hosts: file_servers
  become: true
  tasks:

  - name: install sambab
    tags: samba
    apt:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"    




#  - name: install apache2 and php package
#    apt:
#      name: 
#        - apache2
#        - libapache2-mod-php  
#      state: latest
#      update_cache: yes
#
#    when: ansible_distribution == "Ubuntu"    

